Custom loader support
sivakov512/python-markdown-full-yaml-metadata pull request #20
Opened 2020-12-29 18:25 UTC by Holzhaus

Fixes https://github.com/sivakov512/python-markdown-full-yaml-metadata/issues/18

2021-07-16 21:32 UTC, Holzhaus commented
@sivakov512 firendly ping

2021-07-18 20:21 UTC, sivakov512 commented
Oh, sorry for long (very long) answer.
Do you think that in your case custom loader is better then boolean config option like `full_loader`?

2021-07-18 20:22 UTC, sivakov512 commented
I see that CI does not work here, so code can not be tested. I will fix CI in 1-2 weeks.

2021-07-22 23:06 UTC, sivakov512 commented
@Holzhaus 
I set up a new CI and refactored the project organization a little. Please add tests for this feature.

> Do you think that in your case custom loader is better then boolean config option like full_loader?
What do you think?

2021-07-23 08:14 UTC, Holzhaus commented
For my use case, the boolean flag suffices, other people might want to pass a customized subclass. The boolean flag would be less flexible, but it's your decision ;-)

2021-07-23 08:18 UTC, sivakov512 commented
Okay, your solution sounds better than flag. But it should be tested and documented a bit in `readme`.

2021-07-23 10:45 UTC, Holzhaus commented
Requesting a review is disabled, so pinging you here.

2021-07-23 20:50 UTC, sivakov512 requested changes

2021-07-23 20:50 UTC, sivakov512 commented on tests/test_loaders.py
> +def test_default_loader(
Is is not about default loader, maybe `test_custom_loader`?

2021-07-23 20:50 UTC, sivakov512 commented on tests/test_loaders.py
> +    assert md.convert(SOURCE) == EXPECTED_BODY
This test should check only loader overriding, so remove this assert pls.

2021-07-25 13:22 UTC, Holzhaus commented
I'll take care of #21 after this has been merged.

2021-07-25 21:04 UTC, sivakov512 approved these changes

2021-07-25 21:16 UTC, sivakov512 commented
@Holzhaus, I had an error in CI due to which nothing starts here. Upgrade to the master, please.

2021-07-29 22:20 UTC, merged

2021-07-29 22:20 UTC, sivakov512 commented
@Holzhaus thanks a lot!